{% set name = "coffea" %}
{% set version = "0.7.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coffea-{{ version }}.tar.gz
  sha256: 2516a4a95f01462989c5460ddfb94e4390fadbf291775049804c0faa7e6210b5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flake8
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - awkward >=1.0.1
    - uproot >=4.0.6
    - uproot3-methods >=0.10.0
    - uproot3 >=3.14.1
    - pyarrow >=1.0.0
    - matplotlib-base >=3
    - numba >=0.50.0
    - numpy >=1.16.0
    - scipy >=1.1.0
    - tqdm >=4.27.0
    - lz4
    - cloudpickle >=1.2.3
    - mplhep >=0.1.18
    - packaging
    - fsspec
    - pandas
    - python >=3.6
    - scipy >=1.1.0
    - tqdm >=4.27.0
    - hist >=2.0
    - typing-extensions

test:
  imports:
    - coffea
    - coffea.processor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CoffeaTeam/coffea
  summary: Tools for doing Collider HEP style analysis with columnar operations
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lgray
    - nsmith-
    - areinsvo
    - mcremone
    - chrisburr
