{% set name = "coffea" %}
{% set version = "0.6.49" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coffea-{{ version }}.tar.gz
  sha256: 0b52018537128bff861ae31aaaed0d15a94893fd1b65e3d78d8142b050e48768

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flake8
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - awkward >=0.12.20,<1
    - awkward1 >=0.4.3,<1
    - cloudpickle >=1.2.3
    - ipywidgets
    - lz4
    - matplotlib-base >=3
    - mplhep >=0.1.18
    - numba >=0.50.0
    - numpy >=1.16.0
    - packaging
    - pandas
    - pyarrow >=1.0.0
    - python >=3.6
    - scipy >=1.1.0
    - tqdm >=4.27.0
    - uproot >=3.11.0,<4
    - uproot-methods >=0.7.3,<=0.9
    - uproot4 >=0.0.17,<1

test:
  imports:
    - coffea
    - coffea.analysis_objects
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CoffeaTeam/coffea
  summary: Tools for doing Collider HEP style analysis with columnar operations
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lgray
    - nsmith-
    - areinsvo
    - mcremone
    - chrisburr
